### PR TITLE
improve / update Readme

### PR DESCRIPTION
**Pull request by teutat3s**
- Added helpful info to circumvent "License Terms not found" error when trying to install recent Windows Server eval versions with this `Autounattend.xml`. Credits to @Smithx10 for finding and posting the solution on the IRC #smartos channel.
- Also formatted  Readme to markdown. 

Open for comments, but would be happy if this small contribution could be merged one day.

### CODE REVIEW

**Comment by mgerdts** [comment]
I just merged #6, which affects bhyve/README.  Please incorporate those changes into your version of bhyve/README.md and `git rm bhyve/README`.

**Comment by teutat3s** [comment]
I'll fix this PR then by changing it to rename `README` to `README.md` and incorporate the mentioned changes.

**Comment by teutat3s** [comment]
I believe this PR is better fit for review now - would be happy about another review @mgerdts 
Looking forward for feedback.

**Comment by mgerdts** [comment]
I squashed and merged this in commit 09fe4317624b90fad560c8009a9f3e76c83e197b

**Pull request closed without merging**
